import React from 'react';
import RealWorldData01 from "./img/realworlddata01.png";
import RealWorldData02 from "./img/realworlddata02.png";


const DesignDetails = () => {
  return (
    <section id="details3">
      <div className="details3-container">
        <h2 className='details3-h2'>DESIGN DETAILS</h2>
        <h2 className="details3-header">Game Design</h2>
        <p className="details3-paragraph">
          I took inspiration from the narrative style of <a href="https://www.unep.org/news-and-stories/story/experience-your-carbon-footprint-vr" target="_blank" rel="noopener noreferrer">"Experience Your Carbon Footprint in VR"</a> for "Tide of Food Delivery Waste," using a storytelling approach to engage players by immersing them directly in the experience and making the impact of their actions more tangible.
        </p>
        <h2 className="details3-header">Data Visulization</h2>
        <p className="details3-paragraph">
          The visual format of "Tide of Food Delivery Waste" is inspired by the <a href="https://www.realworldvisuals.com/" target="_blank" rel="noopener noreferrer">"Real World Visuals"</a> project, using comparisons of waste piles or carbon emissions with reference objects to give players a clear sense of the pollution generated by food delivery.
        </p>
        <div className='RealWorldDataImg'>
          <img src={RealWorldData01} className="RealWorldData"></img>
          <img src={RealWorldData02} className="RealWorldData"></img>
        </div>
      </div>
    </section>
  );
};

export default DesignDetails;